name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  canceller:
    runs-on: ubuntu-18.04
    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  tests:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Needed to use the conda environment.
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, 3.9]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # We only install conda to get msprime.
      # When msprime 1.0 is released, we should be able to do away with conda
      # and just pip install msprime (binary wheels for all platforms).
      - name: install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: install dependencies
        run: |
          conda install --yes $(grep numpy requirements.txt) $(grep msprime requirements.txt)
          echo "## pip show numpy"
          pip show numpy
          pip install -r requirements.txt
          echo "## pip show numpy"
          pip show numpy

      - name: run pytest
        run: |
          echo "## pip show numpy"
          pip show numpy
          python -m pytest --cov=demes --cov-report=term-missing -v tests
